### ISSUE TITLE
rsync: connection unexpectedly closed

### ISSUE THREAD

**Issue by nils-werner** [drone-plugins/drone-rsync#4]
deploying using rsync fails with the following message:

```
[info] Pulling image plugins/drone-rsync:latest
$ rsync -az -e ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no /drone/src/myserver/me/drone-4-test/test me@myserver2:public_html
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

I am using settings like

```
deploy:
  rsync:
    user: me
    host: myserver2
    port: 22
    source: start
    target: public_html
```

The only thing that struck me as odd is that `ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no` should be in quotes:

```
rsync -az -e "ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no" /drone/src/myserver/me/drone-4-test/test me@myserver2:public_html
```

but that might be due to quotes being swallowed by the CLI->HTTP->Browser pipeline.

Rsyncing the file from my work machine worked fine (once the quotes were fixed) and the host is pingable from within the container...

**Comment by bradrydzewski** [comment]
the command printed to the console is executed with `exec.Command` which is why we don't need to quote the command line parameters. Can you confirm you've added the Drone ssh key to your server's `authorized_hosts` file, since that would be the primary different between local execution, and execution within the Drone environment

**Comment by nils-werner** [comment]
Bah, of course! That fixed it. I wonder what produces this weird message then. Shouldn't SSH show something more useful?

**Comment by bradrydzewski** [comment]
Yes, the error message that we get back from rsync is definitely vague. I added the error message to the documentation so hopefully it will help others troubleshoot the issue. https://github.com/drone-plugins/drone-rsync/blob/master/DOCS.md#common-problems
